### ISSUE TITLE
receiver renames not visible

### ISSUE THREAD

**Issue by pskiwi** [pskiwi/avr-remote#6]
> 2020-11-29 15:07:21.180 2466-4447/de.pskiwi.avrremote E/avrremote: Read state failed
>     java.io.IOException: Cleartext traffic not permitted: http://192.168.10.30
>         at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:439)
>         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
>         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
>         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
>         at de.pskiwi.avrremote.http.AVRHTTPClient.readState(AVRHTTPClient.java:231)
>         at de.pskiwi.avrremote.http.AVRHTTPClient.readState(AVRHTTPClient.java:212)
>         at de.pskiwi.avrremote.StatusAreaManager$2.run(StatusAreaManager.java:115)

**Comment by pskiwi** [comment]
Fixed by https://github.com/pskiwi/avr-remote/commit/7c120406538c4774dd7316a014390eff89bbc29b
